In [1]:
import pandas as pd # data processing
import numpy as np # working with arrays
import itertools # construct specialized tools
import matplotlib.pyplot as plt # visualizations
from matplotlib import rcParams # plot size customization
from termcolor import colored as cl # text customization
from sklearn.model_selection import train_test_split # splitting the data
from sklearn.linear_model import LogisticRegression # model algorithm
from sklearn.preprocessing import StandardScaler # data normalization
from sklearn.metrics import precision_score # evaluation metric
from sklearn.metrics import classification_report # evaluation metric
from sklearn.metrics import confusion_matrix # evaluation metric
from sklearn.metrics import log_loss # evaluation metric

In [19]:
data = pd.read_csv('ProcedurePrediction.csv')
data

Patient.ID                        FRDPersonnelID      Shift UnitId  \
0           506561  C60CADD0-7A1F-42D7-B90E-687F0364A81E  A - Shift   M438   
1           530126  D2106DC5-10B0-4901-A713-2E08DCEF544B  A - Shift   M438   
2           530212  D2106DC5-10B0-4901-A713-2E08DCEF544B  A - Shift   M438   
3           510809  B0D3C99E-9E01-E211-B5F5-78E7D18CFD3C  A - Shift   M438   
4          1342992  BDD8C99E-9E01-E211-B5F5-78E7D18CFD3C  A - Shift   M438   
...            ...                                   ...        ...    ...   
795189      898016  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C  C - Shift   M423   
795190      899635  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C  C - Shift   M423   
795191      899635  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C  C - Shift   M423   
795192      899644  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C  C - Shift   M423   
795193      899914  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C  C - Shift   M423   

        FireStation Fire.Station.Name             Station.Address  \
0                38  West Centreville             6001 ODay Drive   
1                38  West Centreville             6001 ODay Drive   
2                38  West Centreville             6001 ODay Drive   
3                38  West Centreville             6001 ODay Drive   
4                38  West Centreville             6001 ODay Drive   
...             ...               ...                         ...   
795189           23    West Annandale  8914 Little River Turnpike   
795190           23    West Annandale  8914 Little River Turnpike   
795191           23    West Annandale  8914 Little River Turnpike   
795192           23    West Annandale  8914 Little River Turnpike   
795193           23    West Annandale  8914 Little River Turnpike   

       Station.City Stattion.State Station.Zip.Code  ...  \
0       Centreville       Virginia       20120-1612  ...   
1       Centreville       Virginia       20120-1612  ...   
2       Centreville       Virginia       20120-1612  ...   
3       Centreville       Virginia       20120-1612  ...   
4       Centreville       Virginia       20120-1612  ...   
...             ...            ...              ...  ...   
795189      Fairfax       Virginia       22031-3123  ...   
795190      Fairfax       Virginia       22031-3123  ...   
795191      Fairfax       Virginia       22031-3123  ...   
795192      Fairfax       Virginia       22031-3123  ...   
795193      Fairfax       Virginia       22031-3123  ...   

           Medication.Prescribed Medication_Given_RXCUI_Code  \
0       No Medication Prescribed                         NaN   
1       No Medication Prescribed                         NaN   
2       No Medication Prescribed                         NaN   
3       No Medication Prescribed                         NaN   
4           Medication Presribed                    125464.0   
...                          ...                         ...   
795189  No Medication Prescribed                         NaN   
795190      Medication Presribed                      4337.0   
795191      Medication Presribed                      4337.0   
795192  No Medication Prescribed                         NaN   
795193  No Medication Prescribed                         NaN   

       Medication_Given_Description           FRDPersonnelID...Medication  \
0                                10                                   NaN   
1                                10                                   NaN   
2                                10                                   NaN   
3                                10                                   NaN   
4                                25  0A89F8EB-32DE-4505-9DCA-CF9C68E09DCE   
...                             ...                                   ...   
795189                           10                                   NaN   
795190                          205  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C   
795191                          205  62D3C99E-9E01-E211-B5F

In [20]:
data['Procedure_Performed_Description'].fillna('No procedure', inplace = True)

In [21]:
X = np.asarray(data[['Femaleinteraction', 'Mixedinteraction', 'Maleinteraction', 'Medication_Given_Description', 'tenure']])
y = np.asarray(data['Procedure_Performed_Description'])
print(X, y)

[[ 20  10  10  10   5]
 [ 20  10  10  10   5]
 [ 20  10  10  10   5]
 ...
 [ 10  10  20 205  17]
 [ 10  10  20  10  17]
 [ 10  10  20  10  17]] ['No procedure' 'No procedure' 'No procedure' ...
 'IV Start - Extremity Vein (arm or leg)' 'No procedure' 'No procedure']


In [22]:
X = StandardScaler().fit(X).transform(X)
X

array([[ 3.44352353, -0.95106227, -0.89959884, -0.67018526, -0.8460993 ],
       [ 3.44352353, -0.95106227, -0.89959884, -0.67018526, -0.8460993 ],
       [ 3.44352353, -0.95106227, -0.89959884, -0.67018526, -0.8460993 ],
       ...,
       [-0.29040022, -0.95106227,  1.11160659,  1.69522015,  0.82603439],
       [-0.29040022, -0.95106227,  1.11160659, -0.67018526,  0.82603439],
       [-0.29040022, -0.95106227,  1.11160659, -0.67018526,  0.82603439]])

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 4)

In [24]:
lr = LogisticRegression(C = 0.1, solver = 'liblinear')
lr.fit(X_train,y_train)
lr

LogisticRegression(C=0.1, solver='liblinear')

In [25]:
yhat = lr.predict(X_test)
yhat_prob = lr.predict_proba(X_test)

In [27]:
print(cl(classification_report(y_test, yhat), attrs = ['bold']))

c:\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                                                               precision    recall  f1-score   support

                                       Airway - Clear/Suction       0.00      0.00      0.00      1333
                                Airway - Foreign Body Removal       0.00      0.00      0.00        53
                            Airway - Nasopharyngeal Insertion       0.00      0.00      0.00       920
                                       Airway - Open/Position       0.00      0.00      0.00       372
                             Airway - Oropharyngeal Insertion       0.00      0.00      0.00      1687
                        Airway - Removal of Adjunct (non-ETT)       0.00      0.00      0.00        80
                   Airway - Supraglottic Airway (King, i-Gel)       0.00      0.00      0.00      2230
                   Airway - Supraglottic Airway (i-Gel, King)       0.00      0.00      0.00       841
                               Assess - Assessment of Patient       0.00

c:\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
data = pd.read_csv('MedicationPrediction.csv')
data

Patient.ID                        FRDPersonnelID      Shift UnitId  \
0           506561  C60CADD0-7A1F-42D7-B90E-687F0364A81E  A - Shift   M438   
1           530126  D2106DC5-10B0-4901-A713-2E08DCEF544B  A - Shift   M438   
2           530212  D2106DC5-10B0-4901-A713-2E08DCEF544B  A - Shift   M438   
3           510809  B0D3C99E-9E01-E211-B5F5-78E7D18CFD3C  A - Shift   M438   
4          1342992  BDD8C99E-9E01-E211-B5F5-78E7D18CFD3C  A - Shift   M438   
...            ...                                   ...        ...    ...   
795189      898016  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C  C - Shift   M423   
795190      899635  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C  C - Shift   M423   
795191      899635  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C  C - Shift   M423   
795192      899644  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C  C - Shift   M423   
795193      899914  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C  C - Shift   M423   

        FireStation Fire.Station.Name             Station.Address  \
0                38  West Centreville             6001 ODay Drive   
1                38  West Centreville             6001 ODay Drive   
2                38  West Centreville             6001 ODay Drive   
3                38  West Centreville             6001 ODay Drive   
4                38  West Centreville             6001 ODay Drive   
...             ...               ...                         ...   
795189           23    West Annandale  8914 Little River Turnpike   
795190           23    West Annandale  8914 Little River Turnpike   
795191           23    West Annandale  8914 Little River Turnpike   
795192           23    West Annandale  8914 Little River Turnpike   
795193           23    West Annandale  8914 Little River Turnpike   

       Station.City Stattion.State Station.Zip.Code  ...  \
0       Centreville       Virginia       20120-1612  ...   
1       Centreville       Virginia       20120-1612  ...   
2       Centreville       Virginia       20120-1612  ...   
3       Centreville       Virginia       20120-1612  ...   
4       Centreville       Virginia       20120-1612  ...   
...             ...            ...              ...  ...   
795189      Fairfax       Virginia       22031-3123  ...   
795190      Fairfax       Virginia       22031-3123  ...   
795191      Fairfax       Virginia       22031-3123  ...   
795192      Fairfax       Virginia       22031-3123  ...   
795193      Fairfax       Virginia       22031-3123  ...   

           Medication.Prescribed Medication_Given_RXCUI_Code  \
0       No Medication Prescribed                         NaN   
1       No Medication Prescribed                         NaN   
2       No Medication Prescribed                         NaN   
3       No Medication Prescribed                         NaN   
4           Medication Presribed                    125464.0   
...                          ...                         ...   
795189  No Medication Prescribed                         NaN   
795190      Medication Presribed                      4337.0   
795191      Medication Presribed                      4337.0   
795192  No Medication Prescribed                         NaN   
795193  No Medication Prescribed                         NaN   

        Medication_Given_Description           FRDPersonnelID...Medication  \
0                                NaN                                   NaN   
1                                NaN                                   NaN   
2                                NaN                                   NaN   
3                                NaN                                   NaN   
4                      Normal saline  0A89F8EB-32DE-4505-9DCA-CF9C68E09DCE   
...                              ...                                   ...   
795189                           NaN                                   NaN   
795190  Fentanyl Citrate (Sublimaze)  62D3C99E-9E01-E211-B5F5-78E7D18CFD3C   
795191  Fentanyl Citrate (Sublimaze)  62D3C99E-9E0

In [29]:
data['Medication_Given_Description'].fillna('No Medication', inplace = True)

In [30]:
X = np.asarray(data[['Femaleinteraction', 'Mixedinteraction', 'Maleinteraction', 'Procedure_Performed_Description', 'tenure']])
y = np.asarray(data['Medication_Given_Description'])
print(X, y)

[[ 20  10  10  10   5]
 [ 20  10  10  10   5]
 [ 20  10  10  10   5]
 ...
 [ 10  10  20 130  17]
 [ 10  10  20  10  17]
 [ 10  10  20  10  17]] ['No Medication' 'No Medication' 'No Medication' ...
 'Fentanyl Citrate (Sublimaze)' 'No Medication' 'No Medication']


In [31]:
X = StandardScaler().fit(X).transform(X)
X

array([[ 3.44352353, -0.95106227, -0.89959884, -0.64471312, -0.8460993 ],
       [ 3.44352353, -0.95106227, -0.89959884, -0.64471312, -0.8460993 ],
       [ 3.44352353, -0.95106227, -0.89959884, -0.64471312, -0.8460993 ],
       ...,
       [-0.29040022, -0.95106227,  1.11160659, -0.20634224,  0.82603439],
       [-0.29040022, -0.95106227,  1.11160659, -0.64471312,  0.82603439],
       [-0.29040022, -0.95106227,  1.11160659, -0.64471312,  0.82603439]])

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 4)

In [33]:
lr = LogisticRegression(C = 0.1, solver = 'liblinear')
lr.fit(X_train,y_train)
lr

LogisticRegression(C=0.1, solver='liblinear')

In [34]:
yhat = lr.predict(X_test)
yhat_prob = lr.predict_proba(X_test)

In [35]:
print(cl(classification_report(y_test, yhat), attrs = ['bold']))

c:\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                                     precision    recall  f1-score   support

Acetylsalicylic Acid (Aspirin, ASA)       0.00      0.00      0.00      8222
              Adenosine (Adenocard)       0.00      0.00      0.00       837
               Albuterol (Ventolin)       0.00      0.00      0.00      4840
             Amiodarone (Cordarone)       0.00      0.00      0.00      2301
        Atropine (Atropine Sulfate)       0.00      0.00      0.00       828
             Calcium Chloride (10%)       0.00      0.00      0.00        65
        Cyanokit (Hydroxocobalamin)       0.00      0.00      0.00        29
                Dextrose 10 % (D10)       0.00      0.00      0.00      1557
                Dextrose 50 % (D50)       0.00      0.00      0.00      1456
         Diphenhydramine (Benadryl)       0.00      0.00      0.00       816
   Epinephrine 0.1 MG/ML (1:10,000)       0.37      0.36      0.36     26983
      Epinephrine 1 MG/ML (1:1,000)       0.00      0.00      0.00       79

c:\python\python37\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
